// <auto-generated />
using System;
using DoAn_GiaiDoan1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_GiaiDoan1.Migrations
{
    [DbContext(typeof(QLQKOKDbContext))]
    partial class QLQKOKDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.CaLamViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DVID")
                        .HasColumnType("int");

                    b.Property<int>("DichVuID")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DichVuID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DatPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KHID")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("PhongID");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GioRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioVao")
                        .HasColumnType("datetime2");

                    b.Property<int>("KHID")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<int>("NVID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("PhongID")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("PhongID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.LoaiPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.PhanCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CaLamViecID")
                        .HasColumnType("int");

                    b.Property<int>("NVID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaLamViecID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiPhongID")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiPhongID");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ThanhToan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HDID")
                        .HasColumnType("int");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("DichVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DatPhong", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.KhachHang", "KhachHang")
                        .WithMany("DatPhong")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.Phong", "Phong")
                        .WithMany("DatPhong")
                        .HasForeignKey("PhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.Phong", "Phong")
                        .WithMany("HoaDon")
                        .HasForeignKey("PhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.PhanCong", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.CaLamViec", "CaLamViec")
                        .WithMany("PhanCong")
                        .HasForeignKey("CaLamViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_GiaiDoan1.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.LoaiPhong", "LoaiPhong")
                        .WithMany("Phong")
                        .HasForeignKey("LoaiPhongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.TaiKhoan", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DoAn_GiaiDoan1.Data.TaiKhoan", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.ThanhToan", b =>
                {
                    b.HasOne("DoAn_GiaiDoan1.Data.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.CaLamViec", b =>
                {
                    b.Navigation("PhanCong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.KhachHang", b =>
                {
                    b.Navigation("DatPhong");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.LoaiPhong", b =>
                {
                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("PhanCong");

                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_GiaiDoan1.Data.Phong", b =>
                {
                    b.Navigation("DatPhong");

                    b.Navigation("HoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
